# Generated by Django 3.2.6 on 2021-09-15 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_membership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='products',
            new_name='product',
        ),
    ]
