# Generated by Django 3.2.6 on 2021-09-15 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_membership'),
        ('profiles', '0003_rename_products_membership_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='product',
        ),
        migrations.AddField(
            model_name='membership',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership_product', to='products.product'),
        ),
    ]
