# Generated by Django 3.2.6 on 2021-09-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_membership'),
        ('profiles', '0004_auto_20210915_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='product',
        ),
        migrations.AddField(
            model_name='membership',
            name='product',
            field=models.ManyToManyField(related_name='membership_product', to='products.Product'),
        ),
    ]
