# Generated by Django 3.2.6 on 2021-09-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_discountcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountCode',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='lineitems_total',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='lineitem_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
