# Generated by Django 3.2.6 on 2021-08-31 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='id',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='name',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_membership',
        ),
        migrations.AddField(
            model_name='membership',
            name='is_membership',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='product_ptr',
            field=models.OneToOneField(auto_created=True, default=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product'),
            preserve_default=False,
        ),
    ]
