# Generated by Django 3.2.6 on 2021-09-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_user_profile'),
        ('wish_list', '0002_alter_wishlist_products'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_membership',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
