# Generated by Django 3.2.6 on 2021-09-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210831_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='card_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
