# Generated by Django 3.2.6 on 2021-09-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_is_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='membership',
            field=models.BooleanField(default=False),
        ),
    ]
